name: tbr
description: Unlock the World of Books.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.0
  flutter_form_builder: ^9.1.0
  shared_preferences: ^2.0.7
  smooth_page_indicator: ^1.0.0
  image_picker: ^0.8.4+2
  flutter_spinkit: ^5.1.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.16.0
  provider: ^6.0.5
  fluttertoast: ^8.0.9
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.14.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/splash_logo.jpeg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/splash_logo.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/welcome/
    - assets/logo/
    - assets/profile_pictures/
    - assets/books/
    - assets/images/man.png
